<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/12/30 04:25:18
return array(

  // project
  'baseform' => 'E:/www/365days.me/lib/form/BaseForm.class.php',
  'addphototask' => 'E:/www/365days.me/lib/task/addPhotoTask.class.php',

  // project_model

  // application
  'myuser' => 'E:/www/365days.me/apps/main/lib/myUser.class.php',

  // modules
);
